spawn-command-on-join: false
database:
  mysql: false
  host: ""
  port: ""
  name: ""
  username: ""
  password: ""
  ssl: false
adminmode:
  items:
    rotate:
      name: "&eRotacionar"
      id: 'SLIME_BALL'
    jail:
      name: "&cPrender"
      id: 'NETHER_STAR'
    vanish:
      name: "&9Vanish"
      id: 'POTION'
    cps:
      name: "&aCPS"
      id: 'BLAZE_ROD'
    glass:
      name: "&cAdmin Mode"
      id: 'STAINED_GLASS_PANE'
      data: 15
list:
  show-empty: false
  ignore:
    - 'zToxicDeath_'
    - '_xB0ss'
  roles:
    admin:
      permission: 'servercore.list.administrador'
      name: 'Admin'
    mod:
      permission: 'servercore.list.moderador'
      name: 'Mod'
    helper:
      permission: 'servercore.list.ajudante'
      name: 'Ajudante'
    vip:
      permission: 'servercore.list.vip'
      name: 'Vip'
    youtuber:
      permission: 'servercore.list.youtuber'
      name: 'Youtuber'