spawn-command-on-join: false
database:
  mysql: false
  host: ""
  port: ""
  name: ""
  username: ""
  password: ""
  ssl: false
list:
  show-empty: false
  ignore:
    - 'zToxicDeath_'
    - '_xB0ss'
  roles:
    admin:
      permission: 'servercore.list.administrador'
      name: 'Admin'
    mod:
      permission: 'servercore.list.moderador'
      name: 'Mod'
    helper:
      permission: 'servercore.list.ajudante'
      name: 'Ajudante'
    vip:
      permission: 'servercore.list.vip'
      name: 'Vip'
    youtuber:
      permission: 'servercore.list.youtuber'
      name: 'Youtuber'